/* Базовое изменение статуса истории журнала */
create or replace procedure P_PRECOINEXJRHST_BSET_STATUS
(
  nRN                       in number,       -- Регистрационный номер
  nCOMPANY                  in number,       -- Организация
  sMSG_ID                   in varchar2,     -- Идентификатор сообщения
  sSTATUS                   in varchar2,     -- Статус
  sERR_CODE                 in varchar2,     -- Код ошибки
  sERR_TEXT                 in varchar2,     -- Текст ошибки
  dUPDATED                  in date          -- Дата модификации
)
as
  nPRN                      PKG_STD.tREF;
begin
  /* изменение статуса в таблице */
  update PRECOINEXJRHST
     set MSG_ID = sMSG_ID,
         STATUS = sSTATUS,
         ERR_CODE = sERR_CODE,
         ERR_TEXT = sERR_TEXT,
         UPDATED = dUPDATED
   where RN = nRN
     and COMPANY = nCOMPANY
  returning PRN into nPRN;

  if (SQL%NOTFOUND) then
    PKG_MSG.RECORD_NOT_FOUND( nRN,'PrecoInputExchangeJournalHistory' );
  end if;

  /* изменение статуса в журнале */
  P_PRECOINEXJR_BSET_STATUS( nPRN,nCOMPANY,sMSG_ID,sSTATUS,dUPDATED );
end;
/
show errors procedure P_PRECOINEXJRHST_BSET_STATUS;